import data from '@/content/data.json';
export const stats = data.stats;
export const programs = data.programs;
export const curriculumModules = data.curriculumModules;
export const practicalLearning = data.practicalLearning;
export const differentiators = data.differentiators;
export const certifications = data.certifications;
export const testimonials = data.testimonials;
export const successStories = data.successStories;
export const hiringPartners = data.hiringPartners;
export const careerRoles = data.careerRoles;
export const faqs = data.faqs;
export const tools = data.tools;
export const recognitions = data.recognitions;
