const {MongoClient,Binary}=require('mongodb');
const sharp=require('sharp');
require('@next/env').loadEnvConfig(process.cwd());
const samples=[
 ['AI Marketing','How AI Is Changing Everyday Marketing','AI can help marketers explore ideas and improve workflows while keeping human judgment at the centre.','Begin with a useful problem','Choose one repetitive task, such as grouping customer questions or drafting headline variations. Write down what a good result looks like before selecting a tool.','Keep a human in the loop','Check generated claims, brand tone and customer context. Never publish a draft just because it sounds confident.','Build a repeatable workflow','Save your prompts, record what needed editing and review whether the workflow actually saved time.'],
 ['SEO','A Practical SEO Checklist for Your First Website','Start with search intent, clear pages and a website people can navigate with confidence.','Understand the question','Choose a specific audience question for each page. Make your title and opening paragraph clearly explain what the visitor will learn.','Build useful pages','Use descriptive headings, helpful internal links and original examples. Give every important page a clear path from your navigation.','Review the experience','Check your website on a phone, inspect broken links and compress large images. Useful content works best when visitors can access it easily.'],
 ['Paid Advertising','Planning Your First Google Ads Campaign','A thoughtful campaign starts with a clear offer and a landing page that delivers on the promise.','Define the action','Decide whether the campaign should generate an enquiry, a purchase or a booking. Match the advertisement and landing page to that single action.','Organise your keywords','Group closely related searches and write copy that addresses their intent. Review negative keywords to reduce irrelevant traffic.','Measure before scaling','Confirm conversion tracking works, then review search terms and lead quality. Make small documented changes rather than changing everything at once.'],
 ['Social Media','Building a Content Calendar You Can Actually Maintain','A sustainable calendar turns audience questions into a steady stream of useful ideas.','Choose your themes','Pick three or four topics your audience cares about. Mix education, examples, behind-the-scenes posts and answers to common questions.','Plan a manageable rhythm','Start with a schedule you can maintain. Reserve time for writing, design, review and replies rather than filling every day with a new post.','Learn from responses','Notice which posts start useful conversations. Refine your topics around what people ask and what supports your business goals.'],
 ['Careers','Your First Digital Marketing Portfolio: What to Include','Show how you think, what you created and what you learned from each project.','Tell the project story','Describe the audience, the problem and your role. Explain your choices so a reviewer can understand the reasoning behind the work.','Show the actual work','Include campaign drafts, content plans, page designs or keyword research. Label simulated projects clearly and avoid inventing client results.','Add a reflection','Discuss what you would improve next. A clear account of your learning is more useful than an unsupported claim of success.'],
 ['Analytics','Understanding Marketing Metrics Without the Confusion','Connect each metric to a real decision instead of collecting numbers without a purpose.','Start with the goal','Choose a business question before opening a report. A campaign for enquiries needs different measures from a campaign focused on awareness.','Connect the journey','Look at impressions, visits, actions and lead quality together. A strong click-through rate alone does not explain whether the campaign helped the business.','Write down your next step','Summarise what happened, what might explain it and what you will test. Keep hypotheses separate from facts in your reporting.'],
 ['Email Marketing','Writing Welcome Emails That Feel Human','A good welcome message sets expectations and gives readers one useful next step.','Introduce the relationship','Tell readers why they received the email and what they can expect. Use a recognisable sender name and a straightforward subject line.','Offer something useful','Answer an early question or share a helpful resource. Make the main action clear and keep the message easy to scan on a phone.','Respect the reader','Provide an easy unsubscribe option and avoid misleading promises. Review replies to understand what new subscribers actually need.'],
 ['AI Tools','Better AI Prompts Start with Better Context','Clear context, practical constraints and a defined output make AI-assisted work easier to review.','Explain the task','State the audience, purpose and background. Share the information the model needs without including private customer data.','Describe a useful output','Specify the format, tone and limits. For example, ask for three headline options with a short explanation of the audience each one serves.','Review and iterate','Check the answer against your brief, then refine the prompt. Keep the versions that work and document their limitations.'],
 ['Creative Skills','Designing Landing Pages with a Clear Next Step','Make it easy for visitors to understand the offer and decide what to do next.','Lead with clarity','Explain who the offer is for and the problem it helps solve. Use readable type and a visual hierarchy that works on small screens.','Support the decision','Include relevant details, realistic examples and answers to likely questions. Keep your content specific and avoid claims you cannot support.','Simplify the action','Give the primary button a clear label. Ask only for the information your team needs and explain what happens after a visitor submits the form.'],
 ['Internships','Making the Most of Your Marketing Internship','Treat an internship as a chance to practise, ask questions and develop reliable working habits.','Set learning goals','Choose a few skills to practise and discuss them with your mentor. Ask how your work will be reviewed and where to go when you need help.','Keep a project journal','Record the task, your contribution and the feedback you received. Respect confidentiality when deciding what can go into your portfolio.','Reflect each week','Identify one thing you improved and one thing to work on next. Use that reflection to ask better questions and take on useful responsibilities.'],
];
function lines(title){const words=title.split(' ');const result=[];let line='';for(const word of words){if((line+' '+word).length>31){result.push(line);line=word;}else line=(line+' '+word).trim();}result.push(line);return result;}
async function main(){const client=new MongoClient(process.env.MONGODB_URI);await client.connect();const db=client.db(process.env.MONGODB_DB||'digitonix_academy');let created=0;try{await db.collection('blogs').createIndex({slug:1},{unique:true});for(let i=0;i<samples.length;i++){const [category,title,excerpt,h1,p1,h2,p2,h3,p3]=samples[i];const slug='sample-'+title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/-$/,'');if(await db.collection('blogs').findOne({slug}))continue;const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="720"><rect width="1200" height="720" fill="#14213a"/><circle cx="1090" cy="130" r="230" fill="#233651"/><circle cx="1090" cy="130" r="150" fill="none" stroke="#e8c47a" stroke-width="2"/><path d="M970 0V720M0 590H1200" stroke="#35435a"/><text x="80" y="90" fill="#e8c47a" font-size="20" font-family="sans-serif" letter-spacing="4">DIGITONIX ACADEMY / JOURNAL</text><text x="80" y="205" fill="#c4cee0" font-family="sans-serif" font-size="22">${category.toUpperCase()}</text>${lines(title).map((line,n)=>`<text x="80" y="${295+n*70}" fill="#ffffff" font-size="54" font-family="sans-serif" font-weight="bold">${line.replaceAll('&','&amp;')}</text>`).join('')}<rect x="80" y="630" width="55" height="5" rx="2" fill="#e8c47a"/><text x="157" y="640" fill="#bec8da" font-family="sans-serif" font-size="18">IDEAS FOR YOUR NEXT CHAPTER</text><text x="1070" y="640" fill="#e8c47a" font-size="46" font-family="sans-serif">${String(i+1).padStart(2,'0')}</text></svg>`;const image=await sharp(Buffer.from(svg)).webp({quality:85}).toBuffer();const uploaded=await db.collection('blogImages').insertOne({data:new Binary(image),contentType:'image/webp',width:1200,height:720,createdAt:new Date()});const content=`<p>${excerpt}</p><h2>${h1}</h2><p>${p1}</p><h2>${h2}</h2><p>${p2}</p><h2>${h3}</h2><p>${p3}</p><blockquote>Choose one idea from this article and turn it into a small practical project this week.</blockquote><p><em>Sample article for the Digitonix Academy website. Edit this content in the blog studio before using it as your own editorial material.</em></p>`;const now=new Date();await db.collection('blogs').insertOne({title,slug,excerpt,content,author:'Digitonix Academy',category,coverImage:'/api/images/'+uploaded.insertedId,status:'published',metaTitle:title+' | Digitonix Academy',metaDescription:excerpt,createdAt:now,updatedAt:now,publishedAt:new Date(now.getTime()-i*86400000),sample:true});created++;}console.log(`Created ${created} sample blogs with cover images. Existing samples preserved.`);}finally{await client.close();}}
main().catch(e=>{console.error('Seeding failed: '+e.name);process.exitCode=1;});
