import Link from 'next/link';
import { ArrowUpRight, CheckCircle2, Star } from 'lucide-react';
import type { ContentPage, ContentSection } from '@/lib/content-schema';
import { EnquiryForm } from './enquiry-form';
import { ResourceLibrary } from './resource-library';
import { publishedBlogs } from '@/lib/blogs';

function Buttons({items}:{items:{label:string;href:string}[]}) {return <div className="mt-7 flex flex-wrap gap-3">{items.map((button,index)=><Link key={`${button.href}-${index}`} href={button.href} className={index===0?'academy-hero-primary inline-flex items-center gap-3 rounded-full px-6 py-3 text-sm font-semibold text-white':'inline-flex items-center gap-3 rounded-full border border-[#0f2a6b]/20 bg-white px-6 py-3 text-sm font-semibold text-[#0f2a6b]'}>{button.label}<ArrowUpRight className="h-4 w-4" /></Link>)}</div>;}
function Heading({section:s}:{section:ContentSection}) {return <div className="mb-8 max-w-3xl">{s.eyebrow&&<p className="course-eyebrow">{s.eyebrow}</p>}{s.heading&&<h2 className="mt-4 text-3xl font-semibold leading-tight sm:text-4xl">{s.heading}</h2>}{s.description&&<p className="mt-4 text-sm leading-8 text-[#64708b]">{s.description}</p>}</div>;}
async function Section({section:s}:{section:ContentSection}) {
  if(s.enabled===false)return null;
  if(s.type==='latest-blogs'){
    let posts:Awaited<ReturnType<typeof publishedBlogs>>=[];let unavailable=false;
    try{posts=(await publishedBlogs()).slice(0,s.limit);}catch{unavailable=true;}
    return <section id={s.id} className="section-padding scroll-mt-28 pb-16"><div className="resource-journal-heading"><Heading section={s}/><Link href="/blogs" className="resource-link">{s.allLabel}<ArrowUpRight size={16}/></Link></div><div className="resource-library">{posts.map(post=><Link href={'/blogs/'+post.slug} key={post._id.toString()} className="resource-story">{post.coverImage&&<img src={post.coverImage} alt={post.title} loading="lazy"/>}<div><p className="resource-category">{post.category}</p><h3>{post.title}</h3><p className="resource-description">{post.excerpt}</p><span className="resource-link">{s.linkLabel}<ArrowUpRight size={16}/></span></div></Link>)}</div>{posts.length===0&&<p className="rounded-2xl border bg-white p-8 text-sm">{unavailable?s.unavailableMessage:s.emptyMessage}</p>}</section>;
  }
  if(s.type==='hero')return <section id={s.id} className="section-padding pb-14 pt-32 lg:pt-40">{s.eyebrow&&<span className="course-eyebrow">{s.eyebrow}</span>}<h1 className="mt-6 max-w-4xl text-4xl font-semibold leading-[1.12] tracking-tight sm:text-5xl lg:text-6xl">{s.heading}</h1>{s.description&&<p className="mt-6 max-w-2xl text-base leading-8 text-[#64708b]">{s.description}</p>}<Buttons items={s.buttons} /></section>;
  return <section id={s.id} className="section-padding scroll-mt-28 pb-16">
    {s.type==='cta'?<div className="contact-panel rounded-[2rem] p-8 text-white sm:p-12">{s.eyebrow&&<span className="text-xs font-bold uppercase tracking-widest text-[#f3bd59]">{s.eyebrow}</span>}<h2 className="mt-4 text-3xl font-semibold">{s.heading}</h2><p className="mt-4 max-w-2xl text-sm leading-8 text-[#c5d0e8]">{s.description}</p><Buttons items={s.buttons} /></div>:<>
      {s.type!=='contact'&&<Heading section={s} />}
      {s.type==='resource-library'&&<ResourceLibrary items={s.items} searchPlaceholder={s.searchPlaceholder} emptyMessage={s.emptyMessage} allLabel={s.allLabel}/>}
      {s.type==='stats'&&<div className="grid grid-cols-2 gap-6 rounded-3xl border border-[#0f2a6b]/10 bg-white p-8 sm:grid-cols-4">{s.items.map(item=><div key={item.label} className="text-center"><p className="text-4xl font-semibold text-[#1a3fa0]">{item.value}<span className="text-[#a66a0b]">{item.suffix}</span></p><p className="mt-3 text-xs text-[#64708b]">{item.label}</p></div>)}</div>}
      {s.type==='cards'&&<div className="grid gap-6 md:grid-cols-2">{s.items.map((item,index)=><article key={index} className="flex flex-col overflow-hidden rounded-[1.75rem] border border-[#0f2a6b]/10 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className={`p-7 ${item.highlight?'contact-panel text-white':'bg-[#eef2fb]'}`}>{item.eyebrow&&<p className={`text-xs font-semibold ${item.highlight?'text-[#f3bd59]':'text-[#a66a0b]'}`}>{item.eyebrow}</p>}<h3 className="mt-4 text-2xl font-semibold">{item.title}</h3>{item.detail&&<p className="mt-4 text-xs">{item.detail}</p>}</div><div className="flex flex-1 flex-col p-7"><p className="text-sm leading-7 text-[#64708b]">{item.description}</p>{item.features&&<ul className="mt-5 space-y-3">{item.features.map(feature=><li key={feature} className="flex gap-3 text-sm leading-6 text-[#64708b]"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[#1a3fa0]" />{feature}</li>)}</ul>}{item.href&&<div className="mt-auto pt-6"><Buttons items={[{href:item.href,label:item.linkLabel||item.title}]} /></div>}</div></article>)}</div>}
      {s.type==='modules'&&<div className="grid gap-5 md:grid-cols-2">{s.items.map((module,index)=><details key={index} open={index===0} className="self-start rounded-2xl border border-[#0f2a6b]/10 bg-white p-6"><summary className="cursor-pointer text-base font-semibold"><span className="mr-3 text-xs text-[#a66a0b]">{String(index+1).padStart(2,'0')}</span>{module.title}</summary><p className="my-4 text-xs font-semibold text-[#a66a0b]">{module.category}</p><ul className="space-y-4">{module.items.map(item=><li key={item.name} className="border-l-2 border-[#e8a020]/40 pl-4"><h3 className="text-sm font-semibold">{item.name}</h3><p className="mt-2 text-xs leading-6 text-[#64708b]">{item.desc}</p></li>)}</ul></details>)}</div>}
      {s.type==='features'&&<ul className="grid gap-4 sm:grid-cols-2">{s.items.map((item,index)=><li key={index} className="flex items-start gap-3 rounded-2xl border border-[#0f2a6b]/10 bg-white p-5 text-sm leading-7"><CheckCircle2 className="mt-1.5 h-4 w-4 shrink-0 text-[#1a3fa0]" />{item}</li>)}</ul>}
      {s.type==='testimonials'&&<div className="grid gap-5 md:grid-cols-3">{s.items.map((item,index)=><figure key={index} className="rounded-2xl border border-[#0f2a6b]/10 bg-white p-6"><div aria-label={`${item.rating} out of 5 stars`} className="mb-5 flex gap-1">{Array.from({length:item.rating},(_,i)=><Star key={i} className="h-4 w-4 fill-[#e8a020] text-[#e8a020]" />)}</div><blockquote className="text-sm leading-7 text-[#64708b]">{item.text}</blockquote><figcaption className="mt-6 border-t border-[#0f2a6b]/10 pt-4 text-sm font-semibold">{item.name}<span className="mt-1 block text-xs font-normal text-[#64708b]">{item.role}</span></figcaption></figure>)}</div>}
      {s.type==='faq'&&<div className="space-y-3">{s.items.map((item,index)=><details key={index} className="rounded-2xl border border-[#0f2a6b]/10 bg-white p-6"><summary className="cursor-pointer text-sm font-semibold">{item.question}</summary><p className="mt-4 text-sm leading-7 text-[#64708b]">{item.answer}</p></details>)}</div>}
      {s.type==='contact'&&<div className="overflow-hidden rounded-[2rem] border border-[#0f2a6b]/10 bg-white shadow-xl lg:grid lg:grid-cols-2"><aside className="contact-panel p-8 text-white sm:p-12"><h2 className="text-3xl font-semibold">{s.heading}</h2><p className="mt-5 text-sm leading-7 text-[#c5d0e8]">{s.description}</p><div className="mt-8 space-y-6">{s.contacts.map((contact,index)=><div key={index}><h3 className="mb-2 text-xs font-semibold text-[#f3bd59]">{contact.label}</h3>{contact.href?<Link href={contact.href} className="break-words text-sm leading-7">{contact.value}</Link>:<p className="text-sm leading-7 text-[#c5d0e8]">{contact.value}</p>}</div>)}</div><Buttons items={s.buttons} /></aside><div className="p-8 sm:p-12"><EnquiryForm content={s.form} /></div></div>}
    </>}
  </section>;
}
export function PageRenderer({page}:{page:ContentPage}) {return <div className="course-layout relative isolate overflow-hidden text-[#0f2a6b]"><div aria-hidden="true" className="academy-hero-grid pointer-events-none absolute inset-0 -z-10" />{page.sections.map(section=><Section key={section.id} section={section} />)}</div>;}
