'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Search,ArrowUpRight,FileText,Download,BookOpen } from 'lucide-react';
export type LearningResource={title:string;description:string;category:string;format:string;href:string;linkLabel:string;download?:boolean};
export function ResourceLibrary({items,searchPlaceholder,emptyMessage,allLabel}:{items:LearningResource[];searchPlaceholder:string;emptyMessage:string;allLabel:string}){
 const [category,setCategory]=useState('');const [search,setSearch]=useState('');const categories=Array.from(new Set(items.map(item=>item.category)));const filtered=items.filter(item=>(!category||item.category===category)&&`${item.title} ${item.description} ${item.category}`.toLowerCase().includes(search.toLowerCase()));
 return <div><div className="resource-toolbar"><div className="resource-search"><Search size={18}/><input aria-label={searchPlaceholder} placeholder={searchPlaceholder} value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="resource-filters" role="group" aria-label="Filter resources by topic">{['',...categories].map(value=><button type="button" key={value} aria-pressed={value===category} onClick={()=>setCategory(value)} className={value===category?'selected':''}>{value||allLabel}</button>)}</div></div><div className="resource-library">{filtered.map(item=><article className="resource-card" key={item.href}><div className="resource-card-top"><div className="resource-icon">{item.download?<Download size={23}/>:item.format==='Curriculum'?<BookOpen size={23}/>:<FileText size={23}/>}</div><span>{item.format}</span></div><p className="resource-category">{item.category}</p><h3>{item.title}</h3><p className="resource-description">{item.description}</p>{item.download?<a className="resource-link" href={item.href} download>{item.linkLabel}<Download size={16}/></a>:<Link className="resource-link" href={item.href}>{item.linkLabel}<ArrowUpRight size={16}/></Link>}</article>)}</div>{filtered.length===0&&<p role="status" className="rounded-2xl border bg-white p-8 text-sm text-slate-600">{emptyMessage}</p>}</div>;
}
