import { NextResponse } from 'next/server';
import { isAdmin,sameOrigin } from '@/lib/admin';
import { database } from '@/lib/database';
import { blogSchema,cleanHtml } from '@/lib/blogs';
import { pageSchema } from '@/lib/content-schema';
import { getContentKeys } from '@/lib/content';
import { readFile,writeFile,rename,unlink } from 'node:fs/promises';
import { createHash,randomUUID } from 'node:crypto';
import path from 'node:path';
import { ObjectId } from 'mongodb';
const revision=(raw:string)=>createHash('sha256').update(raw).digest('hex');
const pagePath=(key:string)=>{if(!/^[a-z0-9-]+$/.test(key))throw new Error('Invalid page key');return path.join(process.cwd(),'content','pages',key+'.json');};
let writes:Promise<unknown>=Promise.resolve();
export async function GET(request:Request,{params}:{params:Promise<{resource:string}>}){if(!await isAdmin())return NextResponse.json({error:'Sign in required'},{status:401});try{const {resource}=await params;const url=new URL(request.url);const id=url.searchParams.get('id');if(resource==='pages'){if(id){const raw=await readFile(pagePath(id),'utf8');return NextResponse.json({content:JSON.parse(raw.replace(/^\uFEFF/,'')),revision:revision(raw)});}return NextResponse.json({items:await getContentKeys()});}if(resource!=='blogs'&&resource!=='leads')return NextResponse.json({error:'Unknown resource'},{status:404});const collection=(await database()).collection(resource);if(id&&resource==='blogs'){if(!ObjectId.isValid(id))return NextResponse.json({error:'Invalid ID'},{status:400});return NextResponse.json({item:await collection.findOne({_id:new ObjectId(id)})});}const page=Math.max(1,Number(url.searchParams.get('page'))||1);const items=await collection.find({}).sort({createdAt:-1}).skip((page-1)*20).limit(20).toArray();return NextResponse.json({items,total:await collection.countDocuments(),page});}catch{return NextResponse.json({error:'Unable to load data. Check database configuration or page file.'},{status:503});}}
export async function POST(request:Request,{params}:{params:Promise<{resource:string}>}){if(!await isAdmin())return NextResponse.json({error:'Sign in required'},{status:401});if(!sameOrigin(request))return NextResponse.json({error:'Invalid origin'},{status:403});try{const raw=await request.text();if(raw.length>1000000)return NextResponse.json({error:'Content is too large'},{status:413});const body=JSON.parse(raw);const {resource}=await params;if(resource==='pages'){const content=pageSchema.parse(body.content);const target=pagePath(body.key);const operation=writes.catch(()=>{}).then(async()=>{const existing=await readFile(target,'utf8');if(revision(existing)!==body.revision)throw new Error('CONFLICT');const temp=target+'.'+randomUUID()+'.tmp';try{await writeFile(temp,JSON.stringify(content,null,2)+'\n','utf8');await rename(temp,target);}finally{await unlink(temp).catch(()=>{});}return revision(JSON.stringify(content,null,2)+'\n');});writes=operation;return NextResponse.json({ok:true,revision:await operation});}const db=await database();if(resource==='blogs'){const blog=blogSchema.parse(body);const collection=db.collection('blogs');await collection.createIndex({slug:1},{unique:true});const previous=body.id&&ObjectId.isValid(body.id)?await collection.findOne({_id:new ObjectId(body.id)}):null;const values={...blog,content:cleanHtml(blog.content),updatedAt:new Date(),publishedAt:blog.status==='published'?(previous?.publishedAt||new Date()):null};if(body.id){if(!ObjectId.isValid(body.id))throw new Error('Invalid ID');const result=await collection.updateOne({_id:new ObjectId(body.id)},{$set:values});if(!result.matchedCount)return NextResponse.json({error:'Blog not found'},{status:404});return NextResponse.json({ok:true,id:body.id});}const result=await collection.insertOne({...values,createdAt:new Date()});return NextResponse.json({ok:true,id:result.insertedId.toString()});}if(resource==='leads'){if(!ObjectId.isValid(body.id)||!['new','contacted','qualified','closed'].includes(body.status))throw new Error('Invalid lead status');const result=await db.collection('leads').updateOne({_id:new ObjectId(body.id)},{$set:{status:body.status,updatedAt:new Date()}});return NextResponse.json({ok:result.matchedCount===1});}return NextResponse.json({error:'Unknown resource'},{status:404});}catch(error:any){const conflict=error.message==='CONFLICT';return NextResponse.json({error:conflict?'This page changed. Reload before saving.':error.code===11000?'A blog with this slug already exists.':error.issues?error.issues.map((i:any)=>i.path.join('.')+': '+i.message).join('\n'):'Unable to save. Check your data and database connection.'},{status:conflict?409:error.issues||error.code===11000?400:503});}}

